ping.description=Посмотреть информацию о сервере.
ping.no_description=У сервера отсутствует описание.
ping.cant_retrieve_server=Убедитесь, что IP / порт корректны. Другие возможные решения проблемы:\n\
  1. Указана неверная версия\n\
  2. Сервер офлайн
ping.version_not_found=Версия не найдена, пожалуйста, попробуйте указать другую.
ping.server_info.title=Информация о сервере.
ping.server_info.version=Информация о версии.
ping.server_info.version.unknown=Неизвестный протокол
ping.server_info.players=Информация об игроках.
ping.server_info.players.max=Максимум игроков
ping.server_info.players.online=Онлайн
ping.options.server.description=Сервер, который хотите пингануть.
ping.options.port.description=Порт севера.
ping.options.version.description=Версия сервера.

rcon.description=Команды, связанные с RCON.
rcon.setup.success=RCON был настроен под ваш сервер.
rcon.setup.unsafe_password=Вы указали небезопасный пароль. Поменяйте пароль на вашем RCON и попробуйте снова.
rcon.setup.invalid_ip=Вы ввели неверный айпи. Попробуйте ещё раз, вид айпи (без порта): `0.0.0.0`
rcon.setup.invalid_port=Вы ввели неверный порт. Допустимый разброс значений от 0 до 65535.
rcon.setup.description=Настройка RCON.
rcon.setup.options.ip.description=Айпи вашего RCON.
rcon.setup.options.port.description=Айпи вашего RCON.
rcon.setup.options.password.description=Айпи вашего RCON.
rcon.lookup.description=Посмотреть, какие данные у вашего RCON на данный момент.
rcon.execute.description=Выполнить команду на RCON.
rcon.execute.server_response=Ответ от сервера:
rcon.execute.cant_connect=Извините, но у меня не получается подключиться к серверу.
rcon.execute.missing_permissions=Извините, но у вас нет прав на исполнение RCON команд.
rcon.execute.null_data=Извините, но, кажется, вы забыли настроить RCON.
rcon.execute.command_issued=Команды была выполнена без ответа.
rcon.execute.options.command.description=Команда, которую хотите выполнить.
rcon.restrict.description=Указать пользователя, который сможет позже исполнять RCON команды.
rcon.restrict.options.user.description=Пользователь, который далее будет иметь права на RCON.
rcon.restrict.user_deleted=Пользователь был удален и более не сможет использовать RCON.
rcon.restrict.user_added=Пользователь был добавлен, теперь он сможет использовать RCON.

bridge.toggle.value.enabled=включен
bridge.toggle.value.disabled=выключен
bridge.toggled=Мост был %s
bridge.description=Создаёт мост между майнкрафт и дискорд сервером.
bridge.enable.description=Включить или выключить мост между серверами.
bridge.channel.deleted=Канал более не мост с Майнкрафтом.
bridge.channel.updated=Канал был обновлён.
bridge.channel.not_enough_perms=У бота недостаточно прав, чтобы смотреть/читать данный канал.
bridge.channel.description=Указать канал связывания.
bridge.channel.options.channel.description=Канал для создания моста.
bridge.rcon_not_enabled=Извините, но без RCON мост работать не может. Включите RCON и попробуйте снова.

guideline.support.description=Ссылка на сервер поддержки.
guideline.bridge.description=Помощь в настройке моста.
guideline.bridge.text=\n\
# На данный момент данная информация неактуальна. Это уведомление будет убрано, когда мод/плагин пройдёт проверку.\n\
# Сейчас вы можете его скачать напрямую с GitHub или собрать вручную: <https://github.com/crafter-minecraft/crafter-bridge>.\n\
Итак, чтобы создать мост между Вашим майнкрафт сервером и дискордом, вам лишь нужно установить плагин или мод (в зависимости от ядра сервера): <https://modrinth/plugin/crafter-bridge>.\n\
Так же, это может работать и в обратную сторону: discord -> minecraft. Подробнее об этом в команде /guideline rcon
guideline.rcon.description=Помощь в настройке RCON.
guideline.rcon.text=\n\
# Убедительная просьба:\n\
```\n\
Не пытайтесь делать это самостоятельно, если мало об этом знаете.\n\
Вы можете зайти на наш сервер поддержки (/guideline support) или попросить знающего человека, чтобы вам помогли и обезопасили Ваш сервер.\n\
```\n\
Для настройки RCON вам нужно, для начала, настроить его на самом майнкрафт сервере.\n\
Для этого, зайдите в настройки вашего сервера (server.properties), найдите пункт enable-rcon и измените значение на true, затем вам нужно установить пароль на Ваш RCON. Ищите пункт rcon.password и ставьте пароль.\n\
Далее, по желанию и возможности, меняете rcon.port.

mod.mod.needed_on_client_side=Нужен ли мод на клиенте?
mod.mod.needed_on_server_side=Нужен ли мод на сервере?
mod.mod.game_version=Поддерживаемые версии.
mod.mod.unknown_versions=Версии неизвестны.